{"uuid": "e6f70e0c-051b-41f9-a58d-ff877404e010", "children": ["8d1dfd49-4eb1-4877-94b3-f1c739149565"], "befores": [{"name": "Входим под новым пользователем на сайт", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Failed to decode response from marionette\n\n", "trace": "  File \"c:\\users\\saya\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\saya\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\_pytest\\fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\saya\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\_pytest\\fixtures.py\", line 924, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\Saya\\PycharmProjects\\Diplom\\Diplom_3\\conftest.py\", line 28, in login_new_user\n    login_page.wait_for_load_main_field()\n  File \"c:\\users\\saya\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Saya\\PycharmProjects\\Diplom\\Diplom_3\\pages\\login_page.py\", line 12, in wait_for_load_main_field\n    self.wait_for_visibility(header_login_locator)\n  File \"C:\\Users\\Saya\\PycharmProjects\\Diplom\\Diplom_3\\pages\\base_page.py\", line 12, in wait_for_visibility\n    WebDriverWait(self.driver, 20).until(expected_conditions.visibility_of_element_located(locator))\n  File \"c:\\users\\saya\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 71, in until\n    value = method(self._driver)\n  File \"c:\\users\\saya\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 128, in __call__\n    return _element_if_visible(_find_element(driver, self.locator))\n  File \"c:\\users\\saya\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 415, in _find_element\n    raise e\n  File \"c:\\users\\saya\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 411, in _find_element\n    return driver.find_element(*by)\n  File \"c:\\users\\saya\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 978, in find_element\n    'value': value})['value']\n  File \"c:\\users\\saya\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\saya\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Ожидание загрузки заголовка Вход", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Failed to decode response from marionette\n\n", "trace": "  File \"c:\\users\\saya\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Saya\\PycharmProjects\\Diplom\\Diplom_3\\pages\\login_page.py\", line 12, in wait_for_load_main_field\n    self.wait_for_visibility(header_login_locator)\n  File \"C:\\Users\\Saya\\PycharmProjects\\Diplom\\Diplom_3\\pages\\base_page.py\", line 12, in wait_for_visibility\n    WebDriverWait(self.driver, 20).until(expected_conditions.visibility_of_element_located(locator))\n  File \"c:\\users\\saya\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 71, in until\n    value = method(self._driver)\n  File \"c:\\users\\saya\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 128, in __call__\n    return _element_if_visible(_find_element(driver, self.locator))\n  File \"c:\\users\\saya\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 415, in _find_element\n    raise e\n  File \"c:\\users\\saya\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 411, in _find_element\n    return driver.find_element(*by)\n  File \"c:\\users\\saya\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 978, in find_element\n    'value': value})['value']\n  File \"c:\\users\\saya\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\saya\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1708108372827, "stop": 1708108373914}], "start": 1708108372827, "stop": 1708108373918}], "start": 1708108372827, "stop": 1708108373961}